/* DESAFIO LIVRARIA */

CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(30), 
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR (1),
	NUMERO_DE_PAGINAS CHAR(3), 
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO FLOAT(10,2),
	ESTADO_DA_EDITORA CHAR(2),
	ANO_PUBLICADO CHAR(4)


);

/* Tabela */

INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Cavaleiro Real','Ana Claudia','F','465','Atlas','49.9','RJ','2009');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('SQL para leigos','João Nunes','M','450','Addison','98','SP','2018');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Receitas Caseiras','Celia Tavares','F','210','Atlas','45','RJ','2008');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Pessoas Efetivas','Eduardo Santos','M','390','Beta','78.99','RJ','2018');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Hábitos Saudáveis','Eduardo Santos','M','630','Beta','150.99','RJ','2019');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('A Casa Marrom','Hermes Macedo','M','250','Bubba','60','MG','2016');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Estacio Querido','Geraldo Francisco','M','310','Insignia','100','ES','2015');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Pra Sempre Amigas','Leda Silva','F','510','Insignia','78.99','RS','2011');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('Copas Inesqueciveis','Marcio Alcantara','M','200','Larson','130.98','RS','2018');
INSERT INTO LIVROS (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,NOME_DA_EDITORA,VALOR_DO_LIVRO,ESTADO_DA_EDITORA,ANO_PUBLICADO) VALUES('O poder da mente','Clara Mafra','F','120','Continental','56.58','RS','2017');

/* 1- Trazer todos os dados; */
SELECT NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_PUBLICADO FROM LIVROS;

/* 2- Trazer o nome do livro e o nome da editora; */
SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVROS;

/* 3- Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino */
SELECT NOME_DO_LIVRO, ESTADO_DA_EDITORA FROM LIVROS
WHERE SEXO_DO_AUTOR = 'M';

/* 4- Trazer o nome do livro e o número de paginas dos libros publicados por autores do sexo feminino */
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS
WHERE SEXO_DO_AUTOR = 'F';

/* 5- Trazer o valor dos livros das editoras de São Paulo */
SELECT VALOR_DO_LIVRO FROM LIVROS
WHERE ESTADO_DA_EDITORA = 'SP';
